//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StillAlive.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StillAlive.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAIT|2320
        ///ASCII_ART|Aperture
        ///WAIT|1170
        ///ASCII_ART|Radiation
        ///WAIT|220
        ///ASCII_ART|Aperture
        ///WAIT|760
        ///ASCII_ART|Atom
        ///WAIT|410
        ///ASCII_ART|Aperture
        ///WAIT|1950
        ///ASCII_ART|Heart
        ///WAIT|430
        ///ASCII_ART|Explosion
        ///WAIT|650
        ///ASCII_ART|Fire
        ///WAIT|530
        ///ASCII_ART|Checkmark
        ///WAIT|1000
        ///ASCII_ART|Explosion
        ///WAIT|200
        ///ASCII_ART|Atom
        ///WAIT|240
        ///ASCII_ART|Aperture
        ///
        ///#Page 3
        ///
        ///WAIT|2460
        ///ASCII_ART|BlackMesa
        ///WAIT|980
        ///ASCII_ART|Cake
        ///WAIT|360
        ///ASCII_ART|GLaDOS
        ///WAIT|180
        ///ASCII_ART|Radiation
        ///WAIT|200
        ///ASCII_ART|Aperture        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string art {
            get {
                return ResourceManager.GetString("art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///WAIT|730
        ///DELAY|6
        ///TEXT|&gt;LIST PERSONNEL
        ///TEXT|
        ///TEXT|
        ///TEXT|
        ///TEXT|Gautam Babbar
        ///TEXT|Ted Backman
        ///TEXT|Kelly Bailey
        ///TEXT|Jeff Ballinger
        ///TEXT|Aaron Barber
        ///TEXT|Jeep Barnett
        ///TEXT|Jeremy Bennett
        ///TEXT|Dan Berger
        ///TEXT|Yahn Bernier
        ///TEXT|Ken Birdwell
        ///TEXT|Derrick Birum
        ///TEXT|Mike Blaszczak
        ///TEXT|Iestyn Bleasdale‑Shepherd
        ///TEXT|Chris Bokitch
        ///TEXT|Steve Bond
        ///TEXT|Matt Boone
        ///TEXT|Antoine Bourdon
        ///TEXT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Page 1:
        ///
        ///DELAY|8
        ///TEXT|Forms FORM-29827281-12:
        ///TEXT|Test Assessment Report
        ///TEXT|
        ///TEXT|
        ///DELAY|6
        ///WAIT|370
        ///TEXT|This was a triumph.
        ///WAIT|250
        ///TEXT|I&apos;m making a note here:
        ///WAIT|60
        ///DELAY|8
        ///TEXT|HUGE SUCCESS.
        ///WAIT|180
        ///DELAY|11
        ///TEXT|It&apos;s hard to overstate
        ///DELAY|13
        ///TEXT|my satisfaction.
        ///WAIT|240
        ///DELAY|8
        ///TEXT|Aperture Science
        ///WAIT|250
        ///DELAY|8
        ///TEXT|We do what we must
        ///DELAY|9
        ///TEXT|because we can.
        ///WAIT|200
        ///DELAY|10
        ///TEXT|For the good of all of us.
        ///WAIT|50
        ///DELAY|6
        ///TEXT|Except the ones w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lyrics {
            get {
                return ResourceManager.GetString("lyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Still_Alive {
            get {
                return ResourceManager.GetStream("Still_Alive", resourceCulture);
            }
        }
    }
}
